/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import utils.Functions;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rentalmobil.Login;

/**
 *
 * @author tohsaka
 */
public final class DetailTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     *
     * @param id
     */
    private static String idBukti;
    private static String statusBukti;
    private static String path;
    private static String idOrder;

    public DetailTransaksi(String id) {
        DetailTransaksi.idOrder = id;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        btnDenda.setVisible(false);
        getData(id);
        loadTable(id);
    }

    public void getData(String id) {
        try {
            String query = "SELECT orders.*, users.*, payments.*, user_meta.*, payments.nama AS nama_bank, users.nama AS nama_user FROM orders, users, payments, user_meta\n"
                    + "WHERE orders.id_user = users.id_user AND users.id_user = user_meta.user_id AND orders.id_payment = payments.id_payment AND orders.id_order = '" + id + "'";
            Connection conn = (Connection) Functions.configDB();
            PreparedStatement pst = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet res = pst.executeQuery();
            if (res.next()) {
                System.out.println(res);
                nama.setText(res.getString("nama_user"));
                noOrder.setText(res.getString("id_order"));
                email.setText(res.getString("email"));
                telepon.setText(res.getString("no_telepon"));
                alamat.setText(res.getString("alamat"));
                tanggall.setText(res.getString("created_at"));
                noRek.setText(res.getString("no_rekening"));
                rekening.setText(res.getString("nama_bank"));
                dp.setText(res.getString("dp"));
                subtotal.setText(res.getString("total"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void loadTable(String id) {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("No");
        model.addColumn("ID Bukti");
        model.addColumn("No Order");
        model.addColumn("Nama Bukti");
        model.addColumn("Path");
        model.addColumn("Status");

        int no = 1;
        String sql = "SELECT * FROM order_items "
                + "WHERE order_items.order_id = '" + id + "'";
        try {
            Connection conn = (Connection) Functions.configDB();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                System.out.println(res);
                model.addRow(new Object[]{
                    no++,
                    res.getString("id_order_item"),
                    res.getString("order_id"),
                    res.getString("nama_bukti"),
                    res.getString("gambar_bukti"),
                    res.getString("status")
                });
            }
            jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        noOrder = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tanggall = new javax.swing.JLabel();
        telepon = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        rekening = new javax.swing.JLabel();
        noRek = new javax.swing.JLabel();
        alamat29 = new javax.swing.JLabel();
        alamat31 = new javax.swing.JLabel();
        dp = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        gambarBukti = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        btnDenda = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Detail Transaksi - Rentalkeun Dashboard");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("SF Pro Display Medium", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("RentalKeun");

        jLabel12.setFont(new java.awt.Font("SF Pro Display Medium", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Invoice");

        nama.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        nama.setForeground(new java.awt.Color(51, 51, 51));
        nama.setText("Nama Member");

        noOrder.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        noOrder.setForeground(new java.awt.Color(51, 51, 51));
        noOrder.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        noOrder.setText("No Order");

        email.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 51));
        email.setText("Email");

        tanggall.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        tanggall.setForeground(new java.awt.Color(51, 51, 51));
        tanggall.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tanggall.setText("Tanggal");

        telepon.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        telepon.setForeground(new java.awt.Color(51, 51, 51));
        telepon.setText("No Telp");

        alamat.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        alamat.setForeground(new java.awt.Color(51, 51, 51));
        alamat.setText("Alamat");

        rekening.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        rekening.setForeground(new java.awt.Color(51, 51, 51));
        rekening.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rekening.setText("Rekening");

        noRek.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        noRek.setForeground(new java.awt.Color(51, 51, 51));
        noRek.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        noRek.setText("No Rek");

        alamat29.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        alamat29.setForeground(new java.awt.Color(51, 51, 51));
        alamat29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        alamat29.setText("DP :");

        alamat31.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        alamat31.setForeground(new java.awt.Color(204, 204, 0));
        alamat31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        alamat31.setText("Subtotal :");

        dp.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        dp.setForeground(new java.awt.Color(51, 51, 51));
        dp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dp.setText("Nominal");

        subtotal.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        subtotal.setForeground(new java.awt.Color(204, 204, 0));
        subtotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subtotal.setText("Nominal");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gambarBukti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGo.setBackground(new java.awt.Color(76, 196, 255));
        btnGo.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        btnGo.setForeground(new java.awt.Color(255, 255, 255));
        btnGo.setText("Denda");
        btnGo.setBorderPainted(false);
        btnGo.setFocusPainted(false);
        btnGo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGo.setIconTextGap(10);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnDenda.setBackground(new java.awt.Color(76, 196, 255));
        btnDenda.setFont(new java.awt.Font("SF Pro Display Medium", 1, 15)); // NOI18N
        btnDenda.setForeground(new java.awt.Color(255, 255, 255));
        btnDenda.setText("Konfimasi");
        btnDenda.setBorderPainted(false);
        btnDenda.setFocusPainted(false);
        btnDenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDenda.setIconTextGap(10);
        btnDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDendaActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(0, 178, 255));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/rentalkeun_arrow.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alamat31)
                            .addComponent(alamat29))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dp)
                            .addComponent(subtotal)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12))
                        .addComponent(btnGo)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(alamat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noRek))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(telepon)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rekening))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(email)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggall))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(nama)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noOrder))
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(gambarBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnDenda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(36, 36, 36)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(noOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(tanggall))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telepon)
                    .addComponent(rekening))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat)
                    .addComponent(noRek))
                .addGap(27, 27, 27)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat29)
                    .addComponent(dp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat31)
                    .addComponent(subtotal)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(gambarBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        new Denda(DetailTransaksi.idOrder).setVisible(true);
    }//GEN-LAST:event_btnGoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        DetailTransaksi.idBukti = jTable1.getValueAt(baris, 1).toString();
        DetailTransaksi.path = jTable1.getValueAt(baris, 4).toString();
        DetailTransaksi.statusBukti = jTable1.getValueAt(baris, 5).toString();

        Image icon = new ImageIcon(this.getClass().getResource(DetailTransaksi.path)).getImage();
        Image image = icon.getScaledInstance(345, 222, Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(image);
        gambarBukti.setIcon(ic);

        if (DetailTransaksi.statusBukti.equals("Proses")) {
            btnDenda.setVisible(true);
        } else {
            btnDenda.setVisible(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDendaActionPerformed
        try {
            String query = "UPDATE order_items SET status = 'Selesai' WHERE id_order_item = '" + DetailTransaksi.idBukti + "'";
            Connection conn = (Connection) Functions.configDB();
            PreparedStatement pst = conn.prepareStatement(query);
            pst.execute();
            btnDenda.setVisible(false);
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
            loadTable(DetailTransaksi.idOrder);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnDendaActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTransaksi("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel alamat29;
    private javax.swing.JLabel alamat31;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnDenda;
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel dp;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gambarBukti;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel noOrder;
    private javax.swing.JLabel noRek;
    private javax.swing.JLabel rekening;
    private javax.swing.ButtonGroup roleGroup;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel tanggall;
    private javax.swing.JLabel telepon;
    // End of variables declaration//GEN-END:variables
}
